codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 10%
        threshold: 5%
        paths:
          - "saerojinro-api/src"
          - "saerojinro-domain/src"
          - "saerojinro-admin/src"
          - "saerojinro-speaker/src"
          - "saerojinro-api/src/testFixtures"
          - "saerojinro-domain/src/testFixtures"
          - "saerojinro-admin/src/testFixtures"
          - "saerojinro-speaker/src/testFixtures"
        only_pulls: true
    patch:
      default:
        target: 10%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - dev