-- 1. 독립 테이블: file, "user"
create table file
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    deleted_at    timestamp(6),
    file_size     bigint       not null,
    extension     varchar(255) not null,
    logical_name  varchar(255) not null,
    physical_path varchar(255) not null unique
);

create table "user"
(
    id             bigint generated by default as identity primary key,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6) not null,
    deleted_at     timestamp(6),
    email          varchar(255) not null unique,
    name           varchar(255) not null,
    interest       varchar(255)
        check (interest in
               ('BACKEND', 'FRONTEND', 'AI', 'DATA', 'CLOUD', 'DEVOPS', 'UX_UI', 'SEC', 'PM', 'BLOCKCHAIN', 'MOBILE')),
    oauth_identity varchar(255) unique,
    password       varchar(255),
    profile_image  varchar(255),
    provider       varchar(255)
        check (provider in ('KAKAO', 'GOOGLE')),
    role           varchar(255)
        check (role in ('ATTENDEE', 'SPEAKER', 'ADMIN'))
);

-- 2. speaker는 file에 의존
create table speaker
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6) not null,
    deleted_at    timestamp(6),
    image_file_id bigint       not null unique,
    email         varchar(255) not null unique,
    filmography   varchar(255) not null,
    introduction  varchar(255) not null,
    name          varchar(255) not null,
    position      varchar(255) not null,
    lecture_id    bigint       not null unique,
    foreign key (image_file_id) references file (id)
);

-- 3. lecture는 file과 speaker에 의존
create table lecture
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    start_time        timestamp(6) not null,
    end_time          timestamp(6) not null,
    material_file_id  bigint       not null unique,
    thumbnail_file_id bigint       not null unique,
    speaker_id        bigint       not null unique,
    max_capacity      bigint       not null,
    category          varchar(255) not null
        check (category in
               ('BACKEND', 'FRONTEND', 'AI', 'DATA', 'CLOUD', 'DEVOPS', 'UX_UI', 'SEC', 'PM', 'BLOCKCHAIN', 'MOBILE')),
    contents          varchar(255) not null,
    location          varchar(255) not null,
    title             varchar(255) not null unique,
    foreign key (material_file_id) references file (id),
    foreign key (thumbnail_file_id) references file (id),
    foreign key (speaker_id) references speaker (id)
);

-- speaker에 FK 제약 조건 추가
alter table speaker
    add constraint fk_speaker_lecture
        foreign key (lecture_id) references lecture(id) deferrable initially deferred;


-- 4. lecture와 "user"에 의존하는 테이블들
create table log_event
(
    lecture_id     bigint       not null,
    timestamp      timestamp(6) not null,
    user_id        bigint       not null,
    category       varchar(255) not null
        check (category in
               ('BACKEND', 'FRONTEND', 'AI', 'DATA', 'CLOUD', 'DEVOPS', 'UX_UI', 'SEC', 'PM', 'BLOCKCHAIN', 'MOBILE')),
    log_event_type varchar(255) not null
        check (log_event_type in
               ('LECTURE_VIEW', 'LECTURE_WISHLIST', 'LECTURE_RESERVATION_SUCCESS', 'LECTURE_RESERVATION_FAIL')),
    record         varchar(255) not null primary key,
    foreign key (lecture_id) references lecture (id),
    foreign key (user_id) references "user" (id)
);

create table notification
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    deleted_at timestamp(6),
    user_id    bigint,
    contents   varchar(255) not null,
    title      varchar(255) not null,
    foreign key (user_id) references "user" (id)
);

create table questions
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    deleted_at timestamp(6),
    lecture_id bigint       not null,
    user_id    bigint       not null,
    content    varchar(255) not null,
    foreign key (lecture_id) references lecture (id),
    foreign key (user_id) references "user" (id)
);

create table reservation
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    deleted_at timestamp(6),
    lecture_id bigint       not null,
    user_id    bigint       not null,
    foreign key (lecture_id) references lecture (id),
    foreign key (user_id) references "user" (id)
);

create table wish_list
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    deleted_at timestamp(6),
    lecture_id bigint       not null,
    user_id    bigint       not null,
    foreign key (lecture_id) references lecture (id),
    foreign key (user_id) references "user" (id)
);

create index idx_category_time
    on lecture (category, start_time);

create index idx_start_time
    on lecture (start_time);

create index idx_user_log
    on log_event (user_id asc, timestamp desc);