server:
  port: 8082

spring:
  application:
    name: saerojinro-admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:saerojinro}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

docs:
  api-docs-url: ${API_DOCS_URL:http://localhost:8080/swagger-ui/index.html}
  auth-docs-url: ${AUTH_DOCS_URL:http://localhost:8081/swagger-ui/index.html}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always